//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tStock
    {
        public int fStockId { get; set; }
        [DisplayName("Product Id")]
        public Nullable<int> fProductId { get; set; }

        public Nullable<int> fCount { get; set; }

        [NotMapped]
        public List<tProduct> ProductCollection { get; set; }
    }
}
