//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tUser
    {
        public int fUserId { get; set; }

        [Required(ErrorMessage ="輸入姓名")]
        [DisplayName("姓名")]
        public string fName { get; set; }

        [Required(ErrorMessage = "輸入密碼")]
        [DisplayName("密碼")]
        [DataType(DataType.Password)]

        public string fPassword { get; set; }

        [Required(ErrorMessage = "再次輸入密碼")]
        [DisplayName("確認密碼")]
        [DataType(DataType.Password)]
        [Compare("fPassword",ErrorMessage ="密碼不一致")]
        public string fPassword_confirm { get; set; }

        [DisplayName("是否為管理者")]
        public bool IsAdmin { get; set; }


    }
}
