//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tUser
    {

        public int fUserId { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage ="輸入帳號")]
        public string fName { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "輸入密碼")]
        [DataType(DataType.Password)]
        public string fPassword { get; set; }

        [DisplayName("密碼確認")]
        [Required(ErrorMessage = "再次輸入密碼")]
        [DataType(DataType.Password)]
        [Compare("fPassword",ErrorMessage ="密碼不一致")]
        public string fPassword_confirm { get; set; }

        public bool IsAdmin { get; set; }
    }
}
